Print we do

In [4]:
print('192')

192


Print Name,Id,Studency,Sec

In [3]:
name='Nissan'
id=232311192
Is_student=True
Sec='E'

print(type(name))
print(type(id))
print(type(Is_student))
print(type(Sec))


<class 'str'>
<class 'int'>
<class 'bool'>
<class 'str'>


Input Take

In [6]:
Semester=input("Enter your Semester:" )
print("Your Semester is:",Semester)

Your Semester is: 7th


If I run this, that is not running cause in a python if we not declare the input type pythong take this input as String

In [ ]:
num1=input("Enter first number:")
num2=input("Enter Second number:")
sum=num1+num2
print("The sum of two numbers is:",sum)

That's like type declair

In [3]:
num1=int(input("Enter first number:"))
num2=int(input("Enter first number:"))
sum=(num1+num2)
print("The sum of two numbers is:",sum)

The sum of two numbers is: 2


Array Declaration

In [6]:
Student_Ids=[192,162,163,170,177,196,197,195]
print(Student_Ids)
print(type(Student_Ids))
print(Student_Ids[1])

[192, 162, 163, 170, 177, 196, 197, 195]
<class 'list'>
162


That's Like Id is append

In [14]:
Student_Ids.append(193)
print(Student_Ids)

[192, 162, 163, 170, 177, 196, 197, 195, 193, 175, 193]


In My Previous 10 number possition there is nothing but I insert this in 10th possition 175

In [13]:
Student_Ids.insert(10,175)
print(Student_Ids)

[192, 162, 163, 170, 177, 196, 197, 195, 193, 175]


In My Previous Array two 193 is here but to used remove i removed 193. From the left to write which is come at the first that is removed not at last,Middle or just at the first which see that is delete. remove() is for VALUES (.removed is removed the value of array)

In [15]:
Student_Ids.remove(193)
print(Student_Ids)

[192, 162, 163, 170, 177, 196, 197, 195, 175, 193]


Here the working of pop.Pop is  working to removed the Possition index.Like 192, 162, 163, 170, 177, 196, 197, 195, 175, 193 here if I pop index(10) then my 10 posstion has which value  here that is delete that's mean 193 delete

In [17]:
Student_Ids.pop(9)
print(Student_Ids)

[192, 162, 163, 170, 177, 196, 197, 195, 175]


In [18]:
length=len(Student_Ids)
print(length)

9
